# Change these first
owner: Fahaddz # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

secrets:
  - UPTIME_WAF_KEY
  - CF_ACCESS_CLIENT_ID
  - CF_ACCESS_CLIENT_SECRET
  - PROXMOX
  - PASSMANAGER
  - GLANCE
  - XTREMIO
  - CV_GEN
sites:
  - name: Proxmox
    url: $PROXMOX
    headers:
      - "x-uptime-key: $UPTIME_WAF_KEY"
      - "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET"
    expectedStatusCodes: [200, 204]
  - name: PassManager
    url: $PASSMANAGER
    headers:
      - "x-uptime-key: $UPTIME_WAF_KEY"
      - "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET"
    expectedStatusCodes: [200, 204]
  - name: Glance
    url: $GLANCE
    headers:
      - "x-uptime-key: $UPTIME_WAF_KEY"
      - "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET"
    expectedStatusCodes: [200, 204]
  - name: cv_gen
    url: $CV_GEN
    headers:
      - "x-uptime-key: $UPTIME_WAF_KEY"
      - "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET"
    expectedStatusCodes: [200, 204]
  - name: xTremio
    url: $XTREMIO
    headers:
      - "x-uptime-key: $UPTIME_WAF_KEY"
      - "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET"
    expectedStatusCodes: [200, 204]


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
